import type { NextPage } from 'next'
import { useState, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Category from "../components/Category"

const Home: NextPage = () => {
  const [data, setData] = useState([]);
  const [select, setSelect] = useState({});
  const [modal, setModal] = useState(false);
  const [showBtn, setShowBtn] = useState(false);

  useEffect(() => {
    fetch("/api/ballots", {
      method: "GET",
      headers: {
        "Content-Type": "application/json"
      }
    }).then(res => {
      return res.json()
    }).then(async data => {
      let temp = {};
      await data.items.map(item => {
        temp = {...temp, [item.id]: ""}
        // setSelect({...select, [item.id]: ""});
      })
      setSelect(temp)
      setData(data.items)
    })
  }, [])

  useEffect(() => {
    let temp = 0;
    Object.keys(select).map(function(key, index) {
      if(select[key] !== "") temp++;
    })

    if(temp === 7) setShowBtn(true);
  }, [select])

  const selectCard = async (key, value) => {
    setSelect({
      ...select,
      [key]: value
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <h2 className={styles.title}>
          AWARDS 2021
        </h2>

        {
          data.map((item, index) => <Category selected={select[item.id]} selectCard={selectCard} data={item} key={index} />)
        }
      </div>

      {
        showBtn && (
          <button className={styles.button} onClick={() => setModal(true)}>
            SUBMIT BALLOT BUTTON
          </button>
        )
      }

      {
        modal && (
          <div className={styles.modal}>
            <div className={styles.modalcontent}>
              <span className={styles.close} onClick={() => setModal(false)}>&times;</span>
              <h1 align="center" style={{color: 'black'}}>Success</h1>
            </div>
          </div>
        )
      }
    </div>
  )
}

export default Home
